[env]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.flash_size = 16MB

build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0

lib_deps = fastled/FastLED@^3.10.3



[env:lesson_1_3_blink]
build_src_filter = +<1_3_Blink/>

[env:lesson_1_4_gpio_classwork]
build_src_filter = +<1_4_GPIO_Classwork/>

[env:lesson_1_4_gpio_homework]
build_src_filter = +<1_4_GPIO_Homework/>

[env:lesson_1_5_signals_classwork]
build_src_filter = +<1_5_signals_buttons_classwork/>

[env:lesson_1_5_signals_homework]
build_src_filter = +<1_5_signals_buttons_homework/>

[env:lesson_1_6_LDR]
build_src_filter = +<1_6_ldr/>

[env:lesson_1_6_LDR_homework]
build_src_filter = +<1_6_ldr_homework/>

[env:lesson_1_7_mini_project]
build_src_filter = +<1_7_mini_project/>

[env:lesson_2_1_module_homework]
build_src_filter = +<2_1_module_homework/>

[env:lesson_2_2_module_classwork]
build_src_filter = +<2_2_module_classwork/>